package com.iskcon.folk.app.chantandhear.constant;

public class NamaPrabhuToasts {

    public final static String[] TOAST_MSGS = {
            "I am drinking Nama Prabhu",
            "I love Nama Prabhu",
            "I am embracing Nama Prabhu",
            "I am hearing Nama Prabhu",
            "I soulfully chant Nama Prabhu",
            "I am addicted to Nama Prabhu",
            "I am Nama sevaka",
            "I am Nama premi",
            "I am Nama Sadhaka",
            "I am greedy for Nama Prabhu",
            "I will not leave Nama Prabhu",
            "I trust Nama Prabhu",
            "My only hope is Nama Prabhu",
            "Nama is only my life and soul",
            "I am enveloped in the grace of Nama Prabhu",
            "I cherish every syllable of Nama Prabhu",
            "My heart dances with the vibrations of Nama Prabhu",
            "I find solace in the embrace of Nama Prabhu",
            "I am uplifted by the divine sound of Nama Prabhu",
            "I am immersed in the nectar of Nama Prabhu",
            "I am revitalized by the chanting of Nama Prabhu",
            "I draw strength from the holy name, Nama Prabhu",
            "I am illuminated by the light of Nama Prabhu",
            "I am fulfilled by the eternal joy of Nama Prabhu",
            "I surrender to the love of Nama Prabhu",
            "I thrive in the presence of Nama Prabhu",
            "I find my true self in Nama Prabhu",
            "I am guided by the wisdom of Nama Prabhu",
            "I am purified by the chanting of Nama Prabhu",
            "I am embraced by the mercy of Nama Prabhu",
            "I seek refuge in the shelter of Nama Prabhu",
            "I resonate with the divine energy of Nama Prabhu",
            "I am constantly nourished by Nama Prabhu",
            "I find peace in the eternal name, Nama Prabhu",
            "I am connected to the divine through Nama Prabhu",
            "I am absorbed in the divine rhythm of Nama Prabhu",
            "I awaken to the divine presence in Nama Prabhu",
            "I am consoled by the sacred chant of Nama Prabhu",
            "I bloom in the light of Nama Prabhu",
            "I harmonize my life with the essence of Nama Prabhu",
            "I dwell in the sanctuary of Nama Prabhu",
            "I am inspired by the divine call of Nama Prabhu",
            "I flow with the divine currents of Nama Prabhu",
            "I find eternal bliss in the name of Nama Prabhu",
            "I am drawn to the magnetic charm of Nama Prabhu",
            "I transcend worldly bounds through Nama Prabhu",
            "I blossom in the love of Nama Prabhu",
            "I feel the divine embrace in Nama Prabhu",
            "I am constantly rejuvenated by Nama Prabhu",
            "I reach spiritual heights with Nama Prabhu",
            "I bask in the eternal sunshine of Nama Prabhu",
            "I align my soul with the vibrations of Nama Prabhu",
            "I am nourished by the divine melody of Nama Prabhu",
            "I feel divine joy in every chant of Nama Prabhu",
            "I am anchored in the timeless essence of Nama Prabhu",
            "I discover my true path with Nama Prabhu",
            "I am lifted by the pure essence of Nama Prabhu",
            "I am comforted by the sweet sound of Nama Prabhu",
            "I am intertwined with the divine grace of Nama Prabhu",
            "I find boundless joy in the recitation of Nama Prabhu",
            "I radiate the love of Nama Prabhu",
            "I am in tune with the divine name, Nama Prabhu",
            "I am cradled by the serenity of Nama Prabhu",
            "I am sanctified by the holy name, Nama Prabhu"
    };
}
